

server:
  port: 8000

spring:
  data:
    mongodb:
      uri: mongodb+srv://ani791:Nashik123@mongocluster.olojkhh.mongodb.net/?retryWrites=true&w=majority
      database: tnpPortal

  mail:
    host: smtp.gmail.com
    port: 587
    username: tnpportal17@gmail.com
    password: xwsfnugvpnpyeuyz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


